/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.kontakti.view;
import java.awt.Dimension;
import java.awt.Toolkit;
import ffos.kontakti.controller.ObradaKontakt;
import ffos.kontakti.model.Kontakt;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ffos.kontakti.controller.ObradaVrstaKontakta;
import ffos.kontakti.model.VrstaKontakta;

/**
 *
 * @author Sanja
 */
public class FormaKontakti extends javax.swing.JFrame {
    
    private ObradaKontakt ok;
    private ObradaVrstaKontakta ovk;
    /**
     * Creates new form FormaKontakti
     */
    public FormaKontakti() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        
ok = new ObradaKontakt();
ovk = new ObradaVrstaKontakta();
ucitaj();

    }
    
  
    private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Kontakt k : ok.getKontakti()) {
            m.addElement(k);
        }
        lista.setModel(m);
        
         DefaultComboBoxModel mvk = new DefaultComboBoxModel();
        for(VrstaKontakta vk : ovk.getVrsteKontakta()){
            mvk.addElement(vk);
        }
        vrstaKontakta.setModel(mvk);
}

    
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datumUnosa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ime = new javax.swing.JTextField();
        prezime = new javax.swing.JTextField();
        broj = new javax.swing.JTextField();
        vrstaKontakta = new javax.swing.JComboBox<>();
        dodaj = new javax.swing.JButton();
        promijeni = new javax.swing.JButton();
        obrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FormaKontakti");

        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        jLabel1.setText("Kontakti");

        jLabel2.setText("Datum Unosa:");

        jLabel3.setText("Ime:");

        jLabel4.setText("Prezime:");

        jLabel5.setText("Broj:");

        jLabel6.setText("Vrsta Kontakta:");

        vrstaKontakta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        promijeni.setText("Promijeni");
        promijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promijeniActionPerformed(evt);
            }
        });

        obrisi.setText("Obriši");
        obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ime, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(prezime, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(broj, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(datumUnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(obrisi)
                        .addComponent(dodaj))
                    .addComponent(promijeni)
                    .addComponent(vrstaKontakta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {broj, datumUnosa, dodaj, ime, obrisi, prezime, promijeni, vrstaKontakta});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(prezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(broj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(vrstaKontakta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(datumUnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(dodaj)
                        .addGap(20, 20, 20)
                        .addComponent(promijeni)
                        .addGap(18, 18, 18)
                        .addComponent(obrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        // TODO add your handling code here:
        Kontakt k = new Kontakt();
        k.setIme(ime.getText());
        k.setPrezime(prezime.getText());
        k.setBroj(Integer.parseInt(broj.getText()));
        k.setVrstaKontakta((VrstaKontakta)vrstaKontakta.getSelectedItem());
        k.setDatumUnosa(datumUnosa.getText());
        ok.dodaj(k);
        ucitaj();

    }//GEN-LAST:event_dodajActionPerformed

    private void promijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promijeniActionPerformed
        // TODO add your handling code here:
                try {
            Kontakt k = (Kontakt) lista.getSelectedValue();
            k.setIme(ime.getText());
            k.setPrezime(prezime.getText());
            k.setBroj(Integer.parseInt(broj.getText()));
            k.setVrstaKontakta((VrstaKontakta)vrstaKontakta.getSelectedItem());
            k.setDatumUnosa(datumUnosa.getText());
            ok.promjeni(k);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }

    }//GEN-LAST:event_promijeniActionPerformed

    private void obrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiActionPerformed
        // TODO add your handling code here:
                try {
            Kontakt k = (Kontakt)lista.getSelectedValue();
            ok.obrisi(k);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }


    }//GEN-LAST:event_obrisiActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        // TODO add your handling code here:
        try {
            Kontakt k = (Kontakt)lista.getSelectedValue();
            ime.setText(k.getIme());
            prezime.setText(k.getPrezime());
            datumUnosa.setText(k.getDatumUnosa());
            
            DefaultComboBoxModel m = (DefaultComboBoxModel)vrstaKontakta.getModel();
            
            for(int j=0;j<m.getSize();j++){
                if(k.getVrstaKontakta().getId().equals(((VrstaKontakta)m.getElementAt(j)).getId())){
                vrstaKontakta.setSelectedIndex(j);
                break;
                }    
            }
            
            
        } catch (Exception e) {
        }
  
    }//GEN-LAST:event_listaValueChanged

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listaMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField broj;
    private javax.swing.JTextField datumUnosa;
    private javax.swing.JButton dodaj;
    private javax.swing.JTextField ime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Kontakt> lista;
    private javax.swing.JButton obrisi;
    private javax.swing.JTextField prezime;
    private javax.swing.JButton promijeni;
    private javax.swing.JComboBox<String> vrstaKontakta;
    // End of variables declaration//GEN-END:variables
}
