/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.kontakti.view;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Sanja
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontakti = new javax.swing.JButton();
        vrstaKontakta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izbornik");

        kontakti.setText("Kontakti");
        kontakti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontaktiActionPerformed(evt);
            }
        });

        vrstaKontakta.setText("Vrsta Kontakta");
        vrstaKontakta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrstaKontaktaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(vrstaKontakta)
                .addGap(31, 31, 31)
                .addComponent(kontakti)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrstaKontakta)
                    .addComponent(kontakti))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kontaktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontaktiActionPerformed
        // TODO add your handling code here:
        new FormaKontakti().setVisible(true);
    }//GEN-LAST:event_kontaktiActionPerformed

    private void vrstaKontaktaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrstaKontaktaActionPerformed
        // TODO add your handling code here:
        new FormaVrstaKontakta().setVisible(true);
    }//GEN-LAST:event_vrstaKontaktaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton kontakti;
    private javax.swing.JButton vrstaKontakta;
    // End of variables declaration//GEN-END:variables
}
